name: BankPlusPlus
version: '${version}'
main: dez.fortexx.bankplusplus.BankPlusPlus
api-version: '1.18'
commands:
  bank:
    description: Main bank command

depend:
  - Vault

libraries:
  - com.zaxxer:HikariCP:5.0.1
  - mysql:mysql-connector-java:8.0.33
  - org.snakeyaml:snakeyaml-engine:2.7

permissions:
  bank.use:
    default: op
    children:
      bank.use.withdraw: true
      bank.use.deposit: true
      bank.use.balance: true
  bank.upgrade.all:
    default: op
  bank.interest:
    default: op
  bank.interest.offline:
    default: op
  bank.fees.bypass:
    default: op
    children:
      bank.fees.bypass.deposit: true
      bank.fees.bypass.withdraw: true