name: BankPlusPlus
version: '${version}'
main: dez.fortexx.bankplusplus.BankPlusPlus
api-version: '1.18'
commands:
  bank:
    description: Main bank command

depend:
  - Vault

softdepend:
  - PlaceholderAPI

libraries:
  - com.zaxxer:HikariCP:5.0.1
  - mysql:mysql-connector-java:8.0.33
  - org.snakeyaml:snakeyaml-engine:2.7

permissions:
  bankplusplus.use:
    default: op
  bankplusplus.fees.bypass:
    default: op
    children:
      bankplusplus.fees.bypass.deposit: true
      bankplusplus.fees.bypass.withdraw: true