name: Release
on:
  release:
    types:
      - released
jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: setup-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: get-project-name
        id: extract_project_name
        run: echo "project_name=$(grep 'rootProject.name' settings.gradle | cut -d "'" -f2)" >> $GITHUB_OUTPUT

      - name: jar-with-deps
        run: gradle shadowJar

      - name: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/${{ steps.extract_project_name.outputs.project_name }}.jar


