name: Release
on:
  release:
    types:
      - released
jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: setup-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: get-project-name
        id: extract_project_name
        run: echo "::set-output name=project_name::$(grep 'rootProject.name' settings.gradle | cut -d'"' -f2)"

      - name: jar-with-deps
        run: gradle shadowJar

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/${{ steps.extract_project_name.outputs.project_name }}.jar
          asset_name: ${{ steps.extract_project_name.outputs.project_name }}.jar
          asset_content_type: application/java-archive
          token: ${{ secrets.GITHUB_TOKEN }}


